### ISSUE TITLE
Scroll issue on some pages 

### ISSUE THREAD

**Issue by James-Crisp-UX** [PBGUX/pb-design-system#26]
When the browser height is set to taller than the content but smaller than the content when the header bar has been collapsed scrolling causes a very bad flickering issue. Please see the attached zip file for a demo. 

The issue affects some pages with the class "doc-hero headroom headroom"

[Scroll-issue.webm.zip](https://github.com/PBGUX/bower-designsystem/files/928698/Scroll-issue.webm.zip)

**Comment by smlombardi** [comment]
Have you seen this on other pages?  I assume, also you are using Firefox?

**Comment by James-Crisp-UX** [comment]
I'm using Chrome (v57) on a Mac (OS 10.12)

I've also noticed it on: 
resources/downloads  
web/elements/badges
desktop/patterns/ribbons

Basically it's on any page that has a small amount of content which on larger monitors wouldn't need scrolling. If you shrink the window down so it only just adds the scrollbar and then try to scroll it starts to flicker. I assume that this is because when the doc-hero element collapses down it makes the window smaller than the browser which means that it doesn't need to scroll. This then causes the doc hero to expand again restoring the scrollbars and repeating the process.

**Comment by smlombardi** [comment]
I cannot reproduce it on Safari 10.1 nor Chrome 60.  Since people are not likely to reduce the window to such a small vertical size, we'll have to treat it like a rare edge case.  Thanks.

**Comment by James-Crisp-UX** [comment]
I have reproduced it in Chrome, Safari and Firefox. It doesn't happen at a really small size. It happens on the downloads page with an (internal) browser height between 1080px and 1294px so quite a wide range. I'm happy to have a skype chat if you want to see it happening on my screen.

**Comment by PaulHutson** [comment]
Hi,

I've also managed to reproduce this in Firefox with a large screen (see the screenshot size attached).

Kind regards,
Paul Hutson

![image](https://cloud.githubusercontent.com/assets/5360348/25137616/3af6fd64-2450-11e7-8b05-4f73eff6884c.png)

**Comment by smlombardi** [comment]
It seems to affect pages that do not have a left nav.  We will look at it, thanks.
