### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#27]
Does DS have any guidance on fullscreen support?  I'm looking for guidance on suggested libraries (html5 fullscreen api, 3rd party libs, etc.), icon(s), toggle placement, etc.

**Comment by smlombardi** [comment]
We do not.  Not many products have required this.  Can you be a bit more specific?

**Comment by rdukeshier** [comment]
We have run across this need in several applications within Spectrum, particularly those w/canvases.  These applications are trying to show a large number of nodes on the canvas.  So the goal is to maximize canvas space, typically by minimizing the space used by other components (header, footer, breadcrumbs, etc.).  Right now, we have at least two applications doing this themselves via a homegrown approach (I believe in slightly different ways).  Obviously we would like to be consistent across applications and products.

**Comment by danielcollettepb** [comment]
@rdukeshier I'll send this to @cpileggi via JIRA to determine if this should be added to the DS. Probably won't be in the next DS version. The fullscreen pattern is also used in mapping apps as well, I agree we should have a standard.
