### ISSUE TITLE
Tooltip on hamburger icon push menu is partially hidden

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/pb-design-system#30]
Relay Hub will be using the hamburger icon push menu in DS 3.2.1  (https://designsystem.pitneycloud.com/#/push/icon) in version 2.4.  The tooltip with the nav item name is partially hidden by the hamburger menu.

**Comment by danielcollettepb** [comment]
Adding this as a bug to fix in JIRA, thanks for reporting this.
