### ISSUE TITLE
Tab Wrapping

### ISSUE THREAD

**Issue by ldaug** [PBGUX/pb-design-system#33]
I noticed that when there are around 5 or 6 tabs or more, they wrap to a new line, which makes sense. But the way they shift as the active tab changes is jarring.

![image](https://user-images.githubusercontent.com/7534439/28649599-21382398-7244-11e7-9389-52e34dd1eb85.png)

![image](https://user-images.githubusercontent.com/7534439/28649618-32fc5f68-7244-11e7-82c4-bfe6718389f4.png)

![image](https://user-images.githubusercontent.com/7534439/28649639-4e818b5a-7244-11e7-8041-fc75c03e3eef.png)

**Comment by smlombardi** [comment]
Bootstrap doesn't support 2 rows of tabs.  I would say those are too many tabs, you should consider a different interface.
