### ISSUE TITLE
Large amounts of white space between rows of table in EDGE

### ISSUE THREAD

**Issue by seanprince** [PBGUX/pb-design-system#35]
I'm noticing a difference in behaviour in table row spacing on EDGE (Microsoft Edge 40.15063.0.0, Microsoft EdgeHTML 15.15063) vs Chrome (Version 59.0.3071.115 (Official Build) (64-bit)).

On Chrome:
![image](https://user-images.githubusercontent.com/7532924/28827977-35729ce4-76c7-11e7-9b77-096e848608d8.png)

On EDGE:
![image](https://user-images.githubusercontent.com/7532924/28828013-4f6a2720-76c7-11e7-8a3c-cd459e968b31.png)

ie there's loads of white space on EDGE.

To see the issue in a live application, go here - http://152.144.142.179:8086/bna-client/#/selections .

**Comment by danielcollettepb** [comment]
@seanprince any update on the recommended changes I suggested?

**Comment by seanprince** [comment]
Sorry for the delayed reply - I was off sick at the end of last week.

tooltip-append-to-body didn't work for me - it had the effect of not showing the tooltip at all. However I have resolved the issue by changing:

`<tbody style="height: 450px;">`
to
`<tbody">`

That works in both Chrome and EDGE.

Thanks so much for your help.

**Comment by danielcollettepb** [comment]
Thanks @sean, glad you figured it out... and I hope your feeling better!
