### ISSUE TITLE
Windows 10 - Untrusted Fonts

### ISSUE THREAD

**Issue by ldaug** [PBGUX/pb-design-system#37]
New laptops being built at pb have a policy that is blocking icons from un-trusted sources in IE (and possibly firefox). This affects all webfonts we are delivering with our web apps. It has been logged in Jira as CDQE-59984 and resolved as a System Limitation. But I think this needs more thought and awareness by the ds team, who are choosing these web fonts, as it might not be feasible in all scenarios to ask customers to change their system policies.

https://docs.microsoft.com/en-us/windows/threat-protection/block-untrusted-fonts-in-enterprise#Turn_on_and_use_the_Blocking_untrusted_fonts_feature

![image](https://user-images.githubusercontent.com/7534439/29131523-1bd15c28-7cfb-11e7-8558-41b640565d29.png)

**Comment by irvinm** [comment]
In addition, while there is a work around to just disable this policy, there may be some enterprise customers that will not allow their users to change or modify this behavior, thus rendering our product ineffective.  (Saying that documenting this limitation might not be good enough)

**Comment by rcollette** [comment]
I worked at a company that did this.

**Comment by nickroberts** [comment]
Switch to Chrome! I think this only applies to IE (old IE + Edge), from what I remember. If not...this is not good for the majority of websites these days.

**Comment by ldaug** [comment]
If that was our answer then we would be dropping all IE support...

**Comment by nickroberts** [comment]
Actually, it looks like it doesn't affect Edge...along with the fact that they are telling people not to use it: https://blogs.technet.microsoft.com/secguide/2017/06/15/dropping-the-untrusted-font-blocking-setting/

**Comment by ldaug** [comment]
Not something our company is following right now. Wonder how easy it will be to get them to change it here...

**Comment by nickroberts** [comment]
Based on experience, it is extremely difficult to get anything handled in a timely matter. I wonder if the Security Team might be able to push this along, if they can get the right information, such as the one from that link.

The web version of Office 365 will not even work correctly if this enterprise setting is enabled.
![Office 365 With Font Blocking](https://msdnshared.blob.core.windows.net/media/2017/06/IE-O365-WithFontBlocking.png)

Also, DS's approach is push users towards modern (updating / Evergreen) browsers, especially in the next iteration. These browsers will not have this issue, as they don't use the font rendering that (old) IE (and perhaps most desktop apps) use.

**Comment by danielcollettepb** [comment]
This wouldn't effect just the DS fonts, anything served from Google, FontAwesome, CDN, etc wouldn't display either as @nickroberts points out.

I'll reach out to security team as a next step... thanks for starting this thread @ldaug.

**Comment by danielcollettepb** [comment]
Security team is on it and looped in their IT contact, I will provide limited updates here (remember this is a public repo). I'll send emails to all on this thread if there is more detailed information to share.

**Comment by danielcollettepb** [comment]
Shared this article with the security team, no response on this issue yet:

https://blogs.technet.microsoft.com/secguide/2017/06/15/dropping-the-untrusted-font-blocking-setting/

**Comment by danielcollettepb** [comment]
From security team:

_We are looking on this @ priority. We will update you shortly._

**Comment by danielcollettepb** [comment]
Closing this issue as it should be discussed internally. Please email me if you need help reaching out.
