### ISSUE TITLE
uibpopup positioning issue

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/pb-design-system#38]
I am working on a version of Relay Hub that has a hamburger menu at the left side.  When a view opens there is a button that uses the uib-popover to show a tooltip.  When the view opens after clicking on the hamburger icon the tooltip overlaps the button.  As soon as the mouse is moved the tooltip moves to the correct position.  It may be coincidence but the amount it shifts to the right appears to be about the size of the hamburger menu.  I attached a zip containing screenshots to show what is happening.
[uibpopup.zip](https://github.com/PBGUX/pb-design-system/files/1215116/uibpopup.zip)

**Comment by danielcollettepb** [comment]
Can you share a link to the page **via email** so I can look into why the jump is happening?

I have a story to fix that tooltip being under the leftnav too (as you reported), looks like a z-index issue.

**Comment by jrnorrisjr** [comment]
Sure.  Open https://client.ca.relayhub.pitneycloud.com/

admnautopm@gmail.com/password

Click the templates icon - 3rd one down from the top.

On Thu, Aug 10, 2017 at 10:00 AM, danielcollettepb <notifications@github.com

**Comment by danielcollettepb** [comment]
Can you try setting the popover to `popover-append-to-body="true"`? If that doesn't work I'll have to create a plnkr to figure this out.

**Comment by jrnorrisjr** [comment]
I tried that before - don't remember what it did so I'll try it again.
Think it went under the hamburger.

On Thu, Aug 10, 2017 at 10:42 AM, danielcollettepb <notifications@github.com

**Comment by danielcollettepb** [comment]
OK, there is a really old thread on the the jumping [here](https://github.com/angular-ui/bootstrap/issues/4368), will keep looking for a solution.

**Comment by jrnorrisjr** [comment]
Still the same behavior.  Neil Sampson had me add an offset from the
button.  That doesn't work when the popover is appended to the body which
is why I changed it back.

**Comment by jrnorrisjr** [comment]
BTW. using angular-bootstrap 2.5.0.

**Comment by danielcollettepb** [comment]
Sending you a video via email... issue is related to button animation which you could disable for this specific case.

**Comment by jrnorrisjr** [comment]
Thanks for the help Dan.  Much appreciated.  The CSS animation setting did
the trick.

On Thu, Aug 10, 2017 at 11:24 AM, danielcollettepb <notifications@github.com

**Comment by httpete** [comment]
where / how do you apply this animation-name? I tried a style="" on the button that initiates the popover - my popovers fly in from the right awkwardly.
