### ISSUE TITLE
How to avoid pages jumping left when navigating to long pages

### ISSUE THREAD

**Issue by seanprince** [PBGUX/pb-design-system#39]
When you navigate to a page that doesn't fit on the screen then a scroll bar is shown. The scroll bar is the full height of the screen. That means when you navigate from a short page (that fits) to a long page, then the whole page shifts left by the width of the scroll bar.

You can see this behaviour in the Design System starter application.

You could avoid the jumping left in the header bar  by only showing the scroll bar within the page content (not over the header). Is that recommended?

Are there any recommendations as to designing the height of pages? eg when at 100% zoom, you should aim to design pages that don't need to show a lot of data to fit on the screen?

**Comment by danielcollettepb** [comment]
We recommend following UX best practices, such as in [this UX Myths article](http://uxmyths.com/post/654047943/myth-people-dont-scroll). As noted, the most important content should be at the top of the page (above the fold) and users will scroll.
