### ISSUE TITLE
DS Website Checkboxes example

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/pb-design-system#43]
The website example code for the enhanced checkbox uses the input tag and the checkboxes are not functional.  However, the plunker uses the correct DS directive.

**Comment by danielcollettepb** [comment]
Is this on the Directives page or the Checkbox page? Also, is it the stacked or inline version?

**Comment by jrnorrisjr** [comment]
It's on the checkbox page under enhanced.  The example code on the page is just a standard input with type = "checkbox".  If you click on the Plunker link the code shown uses the DS directive.

**Comment by danielcollettepb** [comment]
thanks, I think we just need to remove the plunkers here (they are linked on the Directives page). The standard inputs can be used with Angular, just need to add ng-model, etc. I'll update the story to fix this. Let me know if you had other thoughts...

**Comment by danielcollettepb** [comment]
this is fixed and will be in the next release
