### ISSUE TITLE
Action List Styling Missing

### ISSUE THREAD

**Issue by rcollette** [PBGUX/pb-design-system#45]
Styling for the following is missing.  Note the use of div and a tags.

```html
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">
    Cras justo odio
  </a>
  <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
  <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
  <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
  <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
</div>
```
https://getbootstrap.com/docs/4.0/components/list-group/#links-and-buttons

**Comment by danielcollettepb** [comment]
I will add a story for this

**Comment by smlombardi** [comment]
@rcollette  Is this for the 5.0 beta?  Because in the bootstrap 3.3.7 documentation, you need to use a `UL` for list groups: https://getbootstrap.com/docs/3.3/components/#list-group

And we _do_ have styling for this: https://designsystem.pitneycloud.com/#/web/basics/typography#list-groups

**Comment by rcollette** [comment]
I was basing it on the 4.0 docs.  But now that you mention it,  DS is probably using BS 3.x
