### ISSUE TITLE
4.1.2 missing in npm

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#49]
npm view pb-design-system still shows 4.1.1 as the latest.  Did we forget to publish 4.1.2?

**Comment by lombardi-gux** [comment]
Looks like.  Thanks, will publish

Not much changed: https://github.com/PBGUX/pb-design-system/blob/master/CHANGELOG.md#412---march-19-2018

**Comment by smlombardi** [comment]
Fixed. 

> A new version of the package pb-design-system (4.1.2) was published at 2018-05-30T17:08:16.476Z
