### ISSUE TITLE
auto-fill value is not supported by IE

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#51]
I updated to beta 7 (from 4) and angular cli gives me the following warning whenever compiling:

```
WARNING in /Users/ri004du/svn/cdqp/trunk/development/webSDK/spectrum-core/node_modules/pb-design-system/dist/css/designsystem.css (/Users/ri004du/svn/cdqp/trunk/development/webSDK/spectrum-core/node_modules/raw-loader!/Users/ri004du/svn/cdqp/trunk/development/webSDK/spectrum-core/node_modules/postcss-loader/lib??embedded!/Users/ri004du/svn/cdqp/trunk/development/webSDK/spectrum-core/node_modules/pb-design-system/dist/css/designsystem.css)
(Emitted value instead of an instance of Error) autoprefixer: /Users/ri004du/svn/cdqp/trunk/development/webSDK/spectrum-core/node_modules/pb-design-system/dist/css/designsystem.css:11:586853: auto-fill value is not supported by IE
```

It's just a warning, but it's quite annoying when running a dev server (via npm start) as the entire command window is eventually filled with this repeated message.

**Comment by smlombardi** [comment]
Found it, I used that feature on one of the "welcome" screens.  I'll switch it back to flexbox.

In the meantime, try installing the latest Autoprefixer and see if the warning goes away:  
`npm i autoprefixer@latest -D`

**Comment by smlombardi** [comment]
@rdukeshier Looks like the last autoprefixer adds support for this in IE.  I just installed it and built, and now when inspecting I see the correct ms syntax:
<img width="574" alt="screen shot 2018-07-12 at 9 12 26 am" src="https://user-images.githubusercontent.com/835148/42635359-e2c1fc86-85b3-11e8-9433-a58d4b8b121a.png">

In any event, we never saw the warning in the first place.

**Comment by rdukeshier** [comment]
@smlombardi I'm still seeing this issue in beta 8.

**Comment by smlombardi** [comment]
We do not see that message.  Ignore the message or find a way to turn it off.

**Comment by rdukeshier** [comment]
@smlombardi @danielcollette @cpileggi Ok, will uninstall design system.

**Comment by lombardi-gux** [comment]
Wise guy.

I will ensure the grid is either removed or behind an @supports for that one page.  Just for you.

**Comment by lombardi-gux** [comment]
Hotfix  pb-design-system@5.0.0-beta.8.0.1<mailto:pb-design-system@5.0.0-beta.8.0.1> published to revert this to flexbox.

**Comment by rdukeshier** [comment]
That fixed it.  Thank you!
