### ISSUE TITLE
ng2-toastr is deprecated

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#52]
5.0 beta 7 currently suggests using [ng2-toastr](https://github.com/PointInside/ng2-toastr) for toaster notifications.  However, this project now shows as deprecated.  Are we sticking with this recommendation or moving to an alternative such as [ngx-toastr](https://github.com/scttcper/ngx-toastr) or [prime-ng](https://www.primefaces.org/primeng/#/toast)?

**Comment by smlombardi** [comment]
Since we're already using PrimeNG, we'll take a look at using theirs.

**Comment by lombardi-gux** [comment]
We have switched to [ngx-toastr](https://github.com/scttcper/ngx-toastr)
