### ISSUE TITLE
Date Picker sample code different than the code used in the demo

### ISSUE THREAD

**Issue by shawnss** [PBGUX/pb-design-system#56]
Sample code uses input-group-btn for date picker button. If we use it then the left side of button will have rounded edges. In the actual code for the demo input-group-append is used which is the correct class to use
![capture](https://user-images.githubusercontent.com/7524790/45836162-0e15c400-bcda-11e8-8582-42431e5c1918.PNG)
![capture](https://user-images.githubusercontent.com/7524790/45836237-41585300-bcda-11e8-8a7a-91b1d2682a7e.PNG)

.

**Comment by smlombardi** [comment]
Thanks, this has been fixed for beta 10
