### ISSUE TITLE
icons missing from conversion tables

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#59]
I noticed some of the icons we use were not in the conversion tables.  Below is a list of these icons.  I have included what I believe to the appropriate pbi icon (when I could find one).

nc-icon-mini
- arrows-1_fullscreen-76
- arrows-1_refresh-69 -> pbi-refresh
- arrows-1_triangle-right-17 -> pbi-play
- arrows-3_small-down -> pbi-minimal-down
- design-2_filter-organization -> pbi-hubvis-tree
- design-2_slider
- design_magnet
- education_paper
- files_archive-check
- files_single-copies -> pbi-duplicate
- files_single-folded-content -> pbi-file
- loader_circle-04 -> pbi-loader-circle
- loader_dots-06 -> pbi-loader
- loader_refresh -> pbi-refresh
- users_circle-10 -> pbi-user
- text_align-justify
- ui-1_check-curve -> pbi-check
- ui-1_lock -> pbi-lock
- ui-1_lock-open -> pbi-unlock
- ui-1_bold-add -> pbi-add
- ui-1_bold-remove -> pbi-close
- ui-2_ban
- ui-2_chat-round-content -> pbi-chat
- ui-2_phone -> pbi-phone
- ui-2_time-clock -> obi-history
- ui-3_playlist

nc-icon-outline
- arrows-1_cloud-download-93 -> pbi-cloud-download
- arrows-1_fullscreen-77 -> pbi-screen-full
- ui-2_grid-45 -> pbi-apps

**Comment by smlombardi** [comment]
Thanks for doing this, we will update.
