### ISSUE TITLE
File tree child nodes icon misalignment

### ISSUE THREAD

**Issue by RobertCurranPB** [PBGUX/pb-design-system#60]
There is a discrepancy between the alignment of the icons for child nodes between the demo site and the code released in 5.0.0-beta.10. Additionally in the demo the children of a folder align left with the folder itself.

![screen shot 2018-10-12 at 09 35 31](https://user-images.githubusercontent.com/44085085/46858191-afd49080-ce02-11e8-9fff-df6cfe5e8484.png)

This can be fixed by updating the padding as follows:

```
.ui-tree .ui-treenode-children {
    margin: 0;
    padding: 0 0 0 2.5em;
}
```

![screen shot 2018-10-15 at 09 37 32](https://user-images.githubusercontent.com/44085085/46939411-1ef9f100-d05e-11e8-8a0c-f81b100fd794.png)

**Comment by danielcollettepb** [comment]
The examples on our site are aligned correctly... Do you have the primeng css included in your project? If so please remove it and let me know if they are aligned correctly. You shouldn't need the primeng css.

![image](https://user-images.githubusercontent.com/6116867/46969008-c6891a80-d082-11e8-8349-279c366683ba.png)

**Comment by RobertCurranPB** [comment]
Ah thanks, we were including the primeng css (as directed by the primeng installation instructions), removing this does make the styles match those on the demo site.

As an improvement to the demo site it might be helpful to include a note about not including the primeng css as this is conflicting with their installation instructions.

That said I still feel the alignment on the demo site is wrong. The children of a nested folder are aligned left with the folder itself. Illustrated by the red line in the image below.

![46969008-c6891a80-d082-11e8-8349-279c366683ba](https://user-images.githubusercontent.com/44085085/47001520-8e391900-d122-11e8-8119-cad096c9f941.png)

To me this seems wrong as I'd expect the children to be indented to the right compared to their parent. Please see examples below from the primeng demo site, the finder application on a Mac.

![screen shot 2018-10-16 at 09 07 49](https://user-images.githubusercontent.com/44085085/47001810-423aa400-d123-11e8-92ac-b644fe794548.png)

![screen shot 2018-10-16 at 09 12 27](https://user-images.githubusercontent.com/44085085/47001996-b2e1c080-d123-11e8-8d7e-6856a33e5cf8.png)

Adding the following rule to our css corrects this alignment of children relative to their parent:

```
.ui-tree .ui-treenode-children {
    margin: 0;
    padding: 0 0 0 2.5em;
}
```

![screen shot 2018-10-16 at 09 13 55](https://user-images.githubusercontent.com/44085085/47002137-179d1b00-d124-11e8-896b-801d45e0d2fe.png)

**Comment by danielcollettepb** [comment]
Agreed, we need to document the primeng css is not required. We'll review this thread and look at the suggested alignment with designers.

**Comment by danielcollettepb** [comment]
We will implement both suggestions in the v5 release, here's a preview of the tree alignment:

![image](https://user-images.githubusercontent.com/6116867/47093416-24d70a00-d1f7-11e8-9c55-3f26cb7d6ceb.png)

Thanks for the feedback, all agreed this looks much better!
