### ISSUE TITLE
header search background color

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#61]
We have received feedback from users that the background color of the header search is too similar to the header background color and is therefore more difficult to see:

![image](https://user-images.githubusercontent.com/5713608/48207927-5a26d180-e337-11e8-97e5-44b700d71d2d.png)

**Comment by smlombardi** [comment]
I'll add it to our backlog.  We got the specs for this from PB.com; we'll re-visit.

**Comment by smlombardi** [comment]
Fixed in 5.1b1
