### ISSUE TITLE
should 3 column welcome page have justified paragraphs?

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#63]
The [demo](https://designsystem.pitneycloud.com/demo/welcome-threecolumn) of the 3-column welcome page has paragraphs with centered text:

![image](https://user-images.githubusercontent.com/5713608/48498114-221e0380-e7fb-11e8-95f9-137dfa71571d.png)

Should this be justified text alignment instead?

**Comment by lombardi-gux** [comment]
Centered, although teams can make it left aligned if they prefer


________________________________
