### ISSUE TITLE
Drag and Drop to Upload component - delete button bug

### ISSUE THREAD

**Issue by szymonworld** [PBGUX/pb-design-system#64]
There is a bug with delete button in FileUpload component from PrimeNG, with icon there is additional ui-btn label. I didn't notest that in official skin from PrimeNG so I'm sure that is Design System bug.

![2018-11-16_10h38_03](https://user-images.githubusercontent.com/9286136/48613419-f2523580-e98b-11e8-8bb7-8beece4474f3.png)

**Comment by smlombardi** [comment]
Have you ensured that you _did not_ include the primeng css file?

**Comment by szymonworld** [comment]
We are not using primeng css in our product, only designsystem. That screenshot is directly from designsystem page (Drag and Drop section).

**Comment by smlombardi** [comment]
Ah.  I did not understand the issue was once an item was adding to the file list.  That's odd, we'll look into it.

**Comment by smlombardi** [comment]
@szymonworld This will be in a patch, but if you need to use it asap, add this to your css:
```
.ui-button-icon-only .ui-button-text {
  display: none !important;
}
```
It is displaying the default text for a button, which is "ui-btn". It adds a text element and an icon element to every button, so it's up to us to hide them in CSS.
