### ISSUE TITLE
expand/collapse all icon request

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#65]
Can we add icons for expand-all & collapse-all?  We're thinking of something like this:  
![image](https://user-images.githubusercontent.com/5713608/48644756-3a338580-e9a9-11e8-83d1-2a14607f6ef1.png)

**Comment by smlombardi** [comment]
@rdukeshier Did those exist in the old font?  Just curious.  I'm sure we can add.

**Comment by rdukeshier** [comment]
I didn't look.  The image above is just pbi-fullscreen and pbi-reduce-screen rotated -45deg.
