### ISSUE TITLE
Text in select is too similar to background color in slate/onyx theme

### ISSUE THREAD

**Issue by szymonworld** [PBGUX/pb-design-system#66]
Text color and background color are white so it's hard to select proper row;

![2018-11-29_12h46_05](https://user-images.githubusercontent.com/9286136/49220025-4f5eda00-f3d5-11e8-8611-98d7ae49725b.png)

**Comment by smlombardi** [comment]
What platform and browser?

That menu is an OS menu, FWIW.

**Comment by szymonworld** [comment]
OS: Windows 10 v1803
Browser: Chrome v70 and Microsoft Edge 42

It works great on Firefox v64

**Comment by szymonworld** [comment]
Also, I notice a similar issue with selected row in PrimeNG table
![2018-11-29_15h56_18](https://user-images.githubusercontent.com/9286136/49230457-09633f80-f3f0-11e8-8038-204ad834b6e5.png)
