### ISSUE TITLE
pbi-screen-reduce renamed to pbi-screen-reduce1

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/pb-design-system#67]
Somewhere between beta 10 and 5.0.1 this icon got renamed.  I've updated our code, but it looks like the DS website still shows the old name on the iconography page.

**Comment by smlombardi** [comment]
Yes, thanks, that's an error it shouldn't have changed.

**Comment by smlombardi** [comment]
Fixed in 5.1b1
