### ISSUE TITLE
Collapsible accordions does not expand on clicking the arrow in Firefox

### ISSUE THREAD

**Issue by vivekmugunthan** [PBGUX/pb-design-system#68]
![screenshot-1](https://user-images.githubusercontent.com/47220739/52069135-ba4a9f80-2543-11e9-9374-f1f653f02cb3.png)

**Comment by smlombardi** [comment]
The arrows are a pseudo element attached to the button that is the title and the rest of the accordion.  These are apparently an issue in Firefox, but work fine in other browsers.

It was intended that users would click on the accordion title
