### ISSUE TITLE
PB Design System website is not working in IE 11

### ISSUE THREAD

**Issue by amitagrawal11** [PBGUX/pb-design-system#69]
Hi Team, 

PB Design System website ( https://ng.designsystem.pitneycloud.com/home ) is not working in IE 11, this might happen because IE does not support ES6. 

For your help, I found following error in IE 11 console :

![image](https://user-images.githubusercontent.com/5697986/57277676-45e34780-70c2-11e9-8637-e105ad1cf41a.png)

I think, we might need to add polyfills to support ES6 javascript.

**Comment by lombardi-gux** [comment]
The Design System website itself might not work in IIE11 , we no longer support it.

The Design System itself, the code that’s distributed to teams, does not include any Javascript to throw this or any other error in a browser.

Does that help?
