### ISSUE TITLE
Search Icon in Header

### ISSUE THREAD

**Issue by shawpb** [PBGUX/pb-design-system#70]
I am a developer on the MapInfo Pro team and we are using the Design system components in an upcoming feature. While testing this, I've 1 issue and 1 concern with the search function of the header control. These points are all visible in the Header demo in the design system.
Issue:
When the header is used in a window that is small enough to show the hamburger menu, The Dropdown menu has a blank line on it that is supposed to be the search option. If the user clicks there, the search input text box is toggled but the user would have to accidentally click there to find that as there is no text or icon to indicate that the row is for the search function. At the very least the dropdown list should show the search icon, or better yet the search icon and a label. 

Concern:
If the user continues to reduce the width of the window, at some point the hamburger dropdown menu changes and starts showing a different search input box. This essentially makes for three separate states for the search function. Perhaps if the hamburger menu always resorted to the "always visible" search control instead of reusing the "toggled" search control, this would provide a little more consistency for the user.

**Comment by smlombardi** [comment]
I'm not sure what you're seeing, as when I go to phone view in Chrome and Safari and click the Hamburger menu, I see the labeled search field instantly.

![dev designsystem pitneycloud com_demo_header(iPhone X) (1)](https://user-images.githubusercontent.com/835148/58910440-88a93700-86e3-11e9-891b-f283fc17430d.png)

I agree it doesn't "kick in" until phone size, perhaps we need to have it appear at a larger beakpoint.

**Comment by smlombardi** [comment]
To fix this, make these changes in the header html:

<img width="1136" alt="Screen Shot 2019-06-04 at 4 17 43 PM" src="https://user-images.githubusercontent.com/835148/58910752-56e4a000-86e4-11e9-9831-3b0d686747dd.png">

**Comment by shawpb** [comment]
I made your recommended changes and now works as I would expect it to. Thanks for the feedback.
