### ISSUE TITLE
Update bootstrap in branch 4.x

### ISSUE THREAD

**Issue by michailw** [PBGUX/pb-design-system#71]
Bootstrap in version 3.3.7 (used by design system 4) is marked as vulnerable.

In attachment, you can see a list of vulnerabilities found by Whitesource.
<img width="1135" alt="Zrzut ekranu 2019-08-9 o 15 08 10" src="https://user-images.githubusercontent.com/5175815/62781157-a0bc7e80-bab7-11e9-9a52-4dcc6a42f25e.png">

Most of these vulnerabilities can be resolved only by an upgrade of Bootstrap to the latest 4.x version, but can we at least update this package to use Bootstrap 3.4.1?

**Comment by smlombardi** [comment]
You can change the entry that gets added to your package.json to 3.4.1 and run npm install.

Updating to 4.x, however, would break much of the CSS in the DS.

**Comment by michailw** [comment]
No, I can't.
My package.json doesn't contain bootstrap, it comes as a dependency of pb-design-system. The only place where it exists is package-lock.json file. I can do changes in package-lock.json, but every time I run npm install, package-lock.json file will be overwritten by default version coming from pb-design-system repository. Vicious circle.

**Comment by smlombardi** [comment]
We will need to examine this further.

**Comment by smlombardi** [comment]
Bootstrap updated to 3.4.1 in the 4.1.5 release  https://github.com/PBGUX/pb-design-system/commit/ff7051e550ba98cae3340cfaff5059fb3682e487
