### ISSUE TITLE
6.0.0-beta.2 - Router animation don't work in IE11 and Edge 42

### ISSUE THREAD

**Issue by szymonworld** [PBGUX/pb-design-system#72]
Router animation don't work in IE11 and Edge 42 using new DS6 beta 2.
Do you have any plans to support these browsers ?

In console I'm getting:
Error: The animation trigger "routerAnimations" has failed to build due to the following errors:
 - The provided animation property "willChange" is not a supported CSS property for animations

**Comment by smlombardi** [comment]
you can remove the `willChange` line in router-animations.ts

we do not support IE11. Edge will soon become Chromium and will be fully supported, although the older Edge should also work fine.
